
================================================================================
FEDERATED LEARNING BENCHMARK - 2025-07-23T06:58:26.052254
Dataset: mnist
Number of clients: 100
Batch size: 32
Local epochs: 5
Desired accuracy: 0.9000
Maximum rounds: 500
Device in use: GPU
  GPU per client: 1.0
[92mINFO [0m:      Starting Flower ServerApp, config: num_rounds=500, no round_timeout
[92mINFO [0m:      
[92mINFO [0m:      [INIT]
[92mINFO [0m:      Using initial global parameters provided by strategy
[92mINFO [0m:      Starting evaluation of initial global parameters
Round 0 - Server-side evaluation: loss 2.6027, accuracy 0.1130
[92mINFO [0m:      initial parameters (loss, other metrics): 2.602660769144694, {'accuracy': 0.113}
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 1]
[92mINFO [0m:      configure_fit: strategy sampled 100 clients (out of 100)
[92mINFO [0m:      aggregate_fit: received 100 results and 0 failures
[93mWARNING [0m:   No fit_metrics_aggregation_fn provided
Round 1 - Server-side evaluation: loss 6.0402, accuracy 0.1130
[92mINFO [0m:      fit progress: (1, 6.0401820487976075, {'accuracy': 0.113}, 214.98887927500004)
[92mINFO [0m:      configure_evaluate: strategy sampled 50 clients (out of 100)
[36m(ClientAppActor pid=11239)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub
[36m(ClientAppActor pid=11239)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).
[92mINFO [0m:      aggregate_evaluate: received 50 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 2]
[92mINFO [0m:      configure_fit: strategy sampled 100 clients (out of 100)
[36m(ClientAppActor pid=11239)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 8x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)[0m
[36m(ClientAppActor pid=11239)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 7x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 7x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 8x across cluster][0m
[92mINFO [0m:      aggregate_fit: received 100 results and 0 failures
Round 2 - Server-side evaluation: loss 3.0980, accuracy 0.2090
[92mINFO [0m:      fit progress: (2, 3.0979856996536257, {'accuracy': 0.209}, 449.873384642)
[92mINFO [0m:      configure_evaluate: strategy sampled 50 clients (out of 100)
[92mINFO [0m:      aggregate_evaluate: received 50 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 3]
[92mINFO [0m:      configure_fit: strategy sampled 100 clients (out of 100)
[36m(ClientAppActor pid=11239)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 4x across cluster][0m
[36m(ClientAppActor pid=11239)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 4x across cluster][0m
[91mERROR [0m:     An exception was raised when processing a message by RayBackend
[91mERROR [0m:     [36mray::ClientAppActor.run()[39m (pid=11240, ip=10.120.17.181, actor_id=22f5c2b2bc5cee3cf99a880301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fad2c237940>)
  File "/home/dd/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11240, ip=10.120.17.181, actor_id=22f5c2b2bc5cee3cf99a880301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fad2c237940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 217, in client_fn
    return FlowerClient(
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 37, in __init__
    self.trainloader, self.valloader, _ = model_utils.get_dataloader(
  File "/home/dd/FLSimulation/FLSimulation/utils.py", line 40, in get_dataloader
    partition = fds.load_partition(partition_id, "train")
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 409, in glob
    return super().glob(path, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 422, in find
    return super().find(
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 532, in info
    paths_info = self._api.get_paths_info(
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3237, in get_paths_info
    hf_raise_for_status(response)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11240, ip=10.120.17.181, actor_id=22f5c2b2bc5cee3cf99a880301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fad2c237940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>
[91mERROR [0m:     Traceback (most recent call last):
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 480, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/dd/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11240, ip=10.120.17.181, actor_id=22f5c2b2bc5cee3cf99a880301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fad2c237940>)
  File "/home/dd/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11240, ip=10.120.17.181, actor_id=22f5c2b2bc5cee3cf99a880301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fad2c237940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 217, in client_fn
    return FlowerClient(
  File "/home/dd/FLSimulation/FLSimulation/federated_learning.py", line 37, in __init__
    self.trainloader, self.valloader, _ = model_utils.get_dataloader(
  File "/home/dd/FLSimulation/FLSimulation/utils.py", line 40, in get_dataloader
    partition = fds.load_partition(partition_id, "train")
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/dd/.local/lib/python3.10/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/dd/.local/lib/python3.10/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 409, in glob
    return super().glob(path, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 422, in find
    return super().find(
  File "/home/dd/.local/lib/python3.10/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 532, in info
    paths_info = self._api.get_paths_info(
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3237, in get_paths_info
    hf_raise_for_status(response)
  File "/home/dd/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11240, ip=10.120.17.181, actor_id=22f5c2b2bc5cee3cf99a880301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fad2c237940>)
  File "/home/dd/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

<!DOCTYPE html>
<html class="" lang="en">
<head>
    <meta charset="utf-8" />
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <meta
            name="description"
            content="We're on a journey to advance and democratize artificial intelligence through open source and open science."
    />
    <meta property="fb:app_id" content="1321688464574422" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@huggingface" />
    <meta
            property="og:title"
            content="Hugging Face - The AI community building the future."
    />
    <meta property="og:type" content="website" />

    <title>Hugging Face - The AI community building the future.</title>
    <style>
        body {
            margin: 0;
        }

        main {
            background-color: white;
            min-height: 100vh;
            padding: 7rem 1rem 8rem 1rem;
            text-align: center;
            font-family: Source Sans Pro, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans,
            sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol,
            Noto Color Emoji;
        }

        img {
            width: 6rem;
            height: 6rem;
            margin: 0 auto 1rem;
        }

        h1 {
            font-size: 3.75rem;
            line-height: 1;
            color: rgba(31, 41, 55, 1);
            font-weight: 700;
            box-sizing: border-box;
            margin: 0 auto;
        }

        p, a {
            color: rgba(107, 114, 128, 1);
            font-size: 1.125rem;
            line-height: 1.75rem;
            max-width: 28rem;
            box-sizing: border-box;
            margin: 0 auto;
        }

        .dark main {
            background-color: rgb(11, 15, 25);
        }
        .dark h1 {
            color: rgb(209, 213, 219);
        }
        .dark p, .dark a {
            color: rgb(156, 163, 175);
        }
    </style>
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        const key = "_tb_global_settings";
        let theme = window.matchMedia("(prefers-color-scheme: dark)").matches
            ? "dark"
            : "light";
        try {
            const storageTheme = JSON.parse(window.localStorage.getItem(key)).theme;
            if (storageTheme) {
                theme = storageTheme === "dark" ? "dark" : "light";
            }
        } catch (e) {}
        if (theme === "dark") {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }
    </script>
</head>

<body>
<main>
    <img
            src="https://cdn-media.huggingface.co/assets/huggingface_logo.svg"
            alt=""
    />
    <div>
        <h1>429</h1>
        <p>We had to rate limit you. If you think it's an error, upgrade to a paid <a href="https://huggingface.co/enterprise" target="_blank">Enterprise Hub</a> account and send us <a href="mailto:website@huggingface.co">an email</a></p>
    </div>
</main>
</body>
</html>

[36m(ClientAppActor pid=11239)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11239)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11239)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11239)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 8x across cluster][0m
[92mINFO [0m:      aggregate_fit: received 99 results and 1 failures
Round 3 - Server-side evaluation: loss 0.5228, accuracy 0.8273
[92mINFO [0m:      fit progress: (3, 0.5228016079266866, {'accuracy': 0.8273333333333334}, 703.0852830669999)
[92mINFO [0m:      configure_evaluate: strategy sampled 50 clients (out of 100)
[92mINFO [0m:      aggregate_evaluate: received 50 results and 0 failures
[92mINFO [0m:      
[92mINFO [0m:      [ROUND 4]
[92mINFO [0m:      configure_fit: strategy sampled 100 clients (out of 100)
[36m(ClientAppActor pid=11240)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 6x across cluster][0m
[36m(ClientAppActor pid=11239)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11239)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub[32m [repeated 8x across cluster][0m
[36m(ClientAppActor pid=11240)[0m Found the latest cached dataset configuration 'mnist' at /home/dd/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Wed Jul 23 07:01:59 2025).[32m [repeated 8x across cluster][0m
[92mINFO [0m:      aggregate_fit: received 100 results and 0 failures
Round 4 - Server-side evaluation: loss 0.1378, accuracy 0.9569

================================================================================
🎉 RESULT: Desired accuracy 0.9000 reached in 4 rounds!
DATASET: mnist, CLIENTS: 100, LOCAL_EPOCHS: 5
Time elapsed: 0:16:01.061830
================================================================================

Combined accuracy plot saved to plots/mnist_100clients_accuracy_plots.png

--- COMPLETE ---
SUCCESS condition met. Terminating simulation for mnist with 100 clients.
